name: Release Build

on:
    push:
        tags: ['v*'] # Triggers on tags starting with 'v'

jobs:
    create-release:
        name: Create Release
        runs-on: ubuntu-latest
        outputs:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
        steps:
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  draft: false
                  prerelease: false

    build:
        name: Build for ${{ matrix.os }}
        needs: create-release
        strategy:
            matrix:
                os: [ubuntu, macos, windows]
                include:
                    - os: ubuntu
                      artifact_name: hk-save-logger-linux
                    - os: macos
                      artifact_name: hk-save-logger-macos
                    - os: windows
                      artifact_name: hk-save-logger-windows.exe
        runs-on: ${{ matrix.os }}-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Build Release
              run: cargo build --release

            - name: Upload Asset to Release
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ needs.create-release.outputs.upload_url }}
                  asset_path: ./target/release/hk-save-logger${{ matrix.os == 'windows' && '.exe' || '' }}
                  asset_name: ${{ matrix.artifact_name }}
                  asset_content_type: application/octet-stream
